data:
  bson_dir: data/ours
  sub_sample: 1.0
logging:
  checkpoint_dir: checkpoints/vqvae
  run_name: vqvae_training
  save_freq: 10
  use_wandb: false
  wandb_project: vqvae-action-chunks
model:
  commitment_cost: 0.25
  hidden_dim: 512
  num_embeddings: 2048
  feature_multiplier: 2
training:
  batch_size: 32
  lr: 0.0005
  num_epochs: 100
  num_samples: 20000
  num_workers: 4
  scheduler_gamma: 0.5
  scheduler_step: 30
